# Generated by Django 4.2.30 on 2026-05-06 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono_alternativo', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('numero_factura', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('impuesto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'compra',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('fecha_validez', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('impuesto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='taller.cliente')),
            ],
            options={
                'db_table': 'cotizacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Motocicleta',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=15, unique=True)),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('cilindraje', models.CharField(blank=True, max_length=20, null=True)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('numero_motor', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_chasis', models.CharField(blank=True, max_length=100, null=True)),
                ('kilometraje_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='taller.cliente')),
            ],
            options={
                'db_table': 'motocicleta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Privilegio',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'privilegio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre', models.CharField(max_length=150)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo_compatible', models.TextField(blank=True, null=True)),
                ('stock_actual', models.IntegerField(blank=True, null=True)),
                ('stock_minimo', models.IntegerField(blank=True, null=True)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ubicacion_almacen', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'producto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('empresa', models.CharField(max_length=150)),
                ('nit', models.CharField(max_length=30)),
                ('contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'proveedor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rol',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('id_rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.DO_NOTHING, to='taller.rol')),
            ],
            options={
                'db_table': 'usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ordentrabajo',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('kilometraje_ingreso', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(blank=True, max_length=30, null=True)),
                ('prioridad', models.CharField(blank=True, max_length=20, null=True)),
                ('costo_mano_obra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('costo_repuestos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='taller.cliente')),
                ('id_cotizacion', models.ForeignKey(blank=True, db_column='id_cotizacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='taller.cotizacion')),
                ('id_mecanico', models.ForeignKey(blank=True, db_column='id_mecanico', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='taller.usuario')),
                ('id_motocicleta', models.ForeignKey(db_column='id_motocicleta', on_delete=django.db.models.deletion.DO_NOTHING, to='taller.motocicleta')),
            ],
            options={
                'db_table': 'ordentrabajo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Notatrabajo',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(blank=True, null=True)),
                ('contenido', models.TextField()),
                ('tipo_nota', models.CharField(blank=True, max_length=50, null=True)),
                ('id_mecanico', models.ForeignKey(db_column='id_mecanico', on_delete=django.db.models.deletion.DO_NOTHING, to='taller.usuario')),
                ('id_orden_trabajo', models.ForeignKey(db_column='id_orden_trabajo', on_delete=django.db.models.deletion.DO_NOTHING, to='taller.ordentrabajo')),
            ],
            options={
                'db_table': 'notatrabajo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Notaservicio',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('total_repuestos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_mano_obra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_general', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado_pago', models.CharField(blank=True, max_length=20, null=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='taller.cliente')),
                ('id_orden_trabajo', models.ForeignKey(db_column='id_orden_trabajo', on_delete=django.db.models.deletion.DO_NOTHING, to='taller.ordentrabajo')),
            ],
            options={
                'db_table': 'notaservicio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('numero_autorizacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('monto_servicio_facturado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('impuesto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_facturado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nit_cliente', models.CharField(max_length=30)),
                ('razon_social', models.CharField(max_length=150)),
                ('id_nota_servicio', models.ForeignKey(db_column='id_nota_servicio', on_delete=django.db.models.deletion.DO_NOTHING, to='taller.notaservicio')),
            ],
            options={
                'db_table': 'factura',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Detalleordentrabajo',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cantidad', models.IntegerField()),
                ('provisto_por_cliente', models.BooleanField(blank=True, null=True)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_orden_trabajo', models.ForeignKey(db_column='id_orden_trabajo', on_delete=django.db.models.deletion.DO_NOTHING, to='taller.ordentrabajo')),
                ('id_producto', models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='taller.producto')),
            ],
            options={
                'db_table': 'detalleordentrabajo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Detallecotizacion',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_cotizacion', models.ForeignKey(db_column='id_cotizacion', on_delete=django.db.models.deletion.DO_NOTHING, to='taller.cotizacion')),
            ],
            options={
                'db_table': 'detallecotizacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Detallecompra',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_compra', models.ForeignKey(db_column='id_compra', on_delete=django.db.models.deletion.DO_NOTHING, to='taller.compra')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.DO_NOTHING, to='taller.producto')),
            ],
            options={
                'db_table': 'detallecompra',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='id_motocicleta',
            field=models.ForeignKey(db_column='id_motocicleta', on_delete=django.db.models.deletion.DO_NOTHING, to='taller.motocicleta'),
        ),
        migrations.AddField(
            model_name='compra',
            name='id_proveedor',
            field=models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.DO_NOTHING, to='taller.proveedor'),
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(blank=True, null=True)),
                ('accion', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='taller.usuario')),
            ],
            options={
                'db_table': 'bitacora',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RolPrivilegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_privilegio', models.ForeignKey(db_column='id_privilegio', on_delete=django.db.models.deletion.DO_NOTHING, to='taller.privilegio')),
                ('id_rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.DO_NOTHING, to='taller.rol')),
            ],
            options={
                'db_table': 'rol_privilegio',
                'managed': True,
                'unique_together': {('id_rol', 'id_privilegio')},
            },
        ),
    ]
